# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=300)),
                ('service_description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='item_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Service'),
        ),
    ]
