# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(default='TestVal', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
